disabled_rules:
  - type_name

opt_in_rules:
  - empty_count

excluded:
  - Clocker/Dependencies
  - Clocker/ClockerUnitTests
  - Clocker/ClockerUITests
  - Clocker/CoreLoggerKit/.build

analyzer_rules:
  - explicit_self

# Severity levels
force_cast: error
force_try:
  severity: error

# Length rules
line_length:
  warning: 160
  error: 200
type_body_length:
  - 300 # warning
  - 600 # error
file_length:
  warning: 600
  error: 900
function_body_length:
  warning: 50
  error: 100

# Nesting
nesting:
  type_level: 2
  function_level: 3

# Naming
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
    - i
    - tz

reporter: "xcode"
