// Copyright © 2015 Abhishek Banthia

import Cocoa

public enum UserDefaultKeys {
    static let emptyString = ""
    static let defaultPreferenceKey = "defaultPreferences"
    static let timezoneName = "formattedAddress"
    static let customLabel = "customLabel"
    static let selectedTimeZoneFormatKey = "is24HourFormatSelected"
    static let dragSessionKey = "public.text"
    static let timezoneID = "timezoneID"
    static let placeIdentifier = "place_id"
    static let relativeDateKey = "relativeDate"
    static let themeKey = "defaultTheme"
    static let showDayInMenu = "showDay"
    static let showDateInMenu = "showDate"
    static let showPlaceInMenu = "showPlaceName"
    static let displayFutureSliderKey = "displayFutureSlider"
    static let startAtLogin = "startAtLogin"
    static let showAppInForeground = "displayAppAsForegroundApp"
    static let sunriseSunsetTime = "showSunriseSetTime"
    static let userFontSizePreference = "userFontSize"
    static let showUpcomingEventView = "ShowUpcomingEventView"
    static let showAllDayEventsInUpcomingView = "showAllDayEventsInUpcomingView"
    static let showMeetingInMenubar = "showMeetingInfoInMenubar"
    static let truncateTextLength = "truncateTextLength"
    static let futureSliderRange = "sliderDayRange"
    static let selectedCalendars = "SelectedCalendars"
    static let showOnboardingFlow = "com.tpak.meridian.showOnboardingFlow"
    static let appDisplayOptions = "com.tpak.meridian.appDisplayOptions"
    static let longStatusBarWarningMessage = "com.tpak.meridian.longStatusBarWarning"
    static let testingLaunchArgument = "isUITesting"
    static let onboardingTestsLaunchArgument = "isTestingTheOnboardingFlow"
    static let menubarCompactMode = "com.tpak.meridian.menubarCompactMode"
    static let defaultMenubarMode = "com.tpak.meridian.shouldDefaultToCompactMode"
    static let installHomeIndicatorObject = "installHomeIndicatorObject"
    static let switchToCompactModeAlert = "com.tpak.meridian.switchToCompactMode"
    static let appleInterfaceStyleKey = "AppleInterfaceStyle"
    // Sync Keys
    static let enableSyncKey = "com.tpak.meridian.enableSync"
    static let ubiquitousStoreLastUpdateKey = "com.tpak.meridian.ubiquitousLastUpdateKey"
    static let userDefaultsLastUpdateKey = "com.tpak.meridian.defaultsLastUpdateKey"
}
